FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json nx.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs

RUN npm ci
RUN npx nx build web

FROM caddy:2-alpine

COPY infra/docker/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/apps/web/build/client /srv

EXPOSE 80 443
